##  HMM 
- Bảng mật độ phân phối của quan sát cho mỗi trạng thái E
- Bảng mdppxs khi chuyển trạng thái T
- Bảng mdppxs chi chọn trạng thái bắt đầu S0 
<img src="hmm.png">

In [14]:
import numpy as np

              #Party #TV  #Pub #Study
E = np.array([[0.3, 0.2, 0.4, 0.3 ], #Tired
              [0.4, 0.1, 0.2, 0.05], #Hungover
              [0.2, 0.2, 0.1, 0.3 ], #Scared
              [0.1, 0.5, 0.3, 0.35]  #Fine
            ])

              #Party #TV  #Pub #Study
T = np.array([[0.05, 0.7, 0.05, 0.2 ], #Party
              [0.1 , 0.4, 0.3 , 0.2 ], #TV
              [0.1 , 0.6, 0.05, 0.25], #Pub
              [0.25, 0.3, 0.4 , 0.05]  #Study
             ])

              #Party #TV  #Pub #Study
S0 = np.array([0.25, 0.25, 0.25, 0.25]).T

## Forward
- Tính được xác suất của dãy quan sát: Tired -> Tired -> Scared

In [10]:
#Tired
S1 = S0 * E[0]
print(S1)

[0.075 0.05  0.1   0.075]


In [13]:
#Tired
S2 = T.T.dot(S1)*E[0]
print(S2)

[0.01125  0.031    0.0215   0.016125]


In [12]:
#Scared
S3 = T.T.dot(S2)*E[2]
print(S3)

[0.00196875 0.0076025  0.00173875 0.00438938]


## Viterbi
- Xác định chuỗi trạng thái từ chuỗi quan sát: Tired -> Tired -> Scared